name: Publish Docker Image

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write    # para criar tags e releases

env:
  REGISTRY: docker.io
  IMAGE_NAME: arthurferroni/approachti-quepasa
  NODE_ENV: production
  APP_ENV: production
  QUEPASA_CONTAINER_NAME: "quepasa"
  QUEPASA_HOST_NAME: "quepasa"
  QUEPASA_MEMORY_LIMIT: 512M
  QUEPASA_EXTERNAL_PORT: 31000
  QUEPASA_INTERNAL_PORT: 31000
  WEBAPIPORT: 31000
  QUEPASA_BASIC_AUTH_USER: ${{ secrets.DOCKER_USERNAME }}
  QUEPASA_BASIC_AUTH_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  MIGRATIONS: './migrations'
  WEBSOCKETSSL: false

jobs:
  push_to_registry:
    name: Push Docker + GitHub Release (condicional)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1) Build & push apenas com `latest`
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=schedule
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          flavor: |
            latest=true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 2) Só prossiga se for push na main
      - name: Extract old QpVersion
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: extract_old
        run: |
          OLD=$(git show HEAD~1:src/models/qp_defaults.go \
            | grep -Po '(?<=const QpVersion = ")[^"]+')
          echo "old=$OLD" >> $GITHUB_OUTPUT

      - name: Extract new QpVersion
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: extract_new
        run: |
          NEW=$(grep -Po '(?<=const QpVersion = ")[^"]+' src/models/qp_defaults.go)
          echo "new=$NEW" >> $GITHUB_OUTPUT
          echo "VERSION=$NEW" >> $GITHUB_ENV

      # 3) Se QpVersion mudou, crie tag, Release e tagueie a imagem
      - name: Configure Git for tagging
        if: ${{ steps.extract_old.outputs.old != steps.extract_new.outputs.new }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create & push Git tag ${{ env.VERSION }}
        if: ${{ steps.extract_old.outputs.old != steps.extract_new.outputs.new }}
        run: |
          git tag -a "${{ env.VERSION }}" -m "Release ${{ env.VERSION }}"
          git push origin "${{ env.VERSION }}"

      - name: Create GitHub Release ${{ env.VERSION }}
        if: ${{ steps.extract_old.outputs.old != steps.extract_new.outputs.new }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            📦 Imagem Docker `${{ env.IMAGE_NAME }}:${{ env.VERSION }}` publicada!
            Commit: ${{ github.sha }}

      - name: Build & push Docker image with version tag
        if: ${{ steps.extract_old.outputs.old != steps.extract_new.outputs.new }}
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
